---
name: Close stale issues and PRs
on:
  schedule:
    - cron: "42 4 * * 1-5"
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-stale: 12
          days-before-close: 4
          exempt-pr-labels: "dependencies,security"
          stale-issue-message: "Issue will be marked as stale because it has not been updated in a while"
          stale-pr-message: "PR will be marked as stale because it has not been updated in a while"
